name: Ruby

env:
  WORLD_TIME_API_KEY: ${{ vars.WORLD_TIME_API_KEY }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        ruby-version: ["2.7.1"]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Print Envs
        run: printenv WORLD_TIME_API_KEY

      - name: Run tests
        run: bundle exec rspec
